version: "3.8"
services:

    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        ports:
            - "3434:3306"
    wordpress:
        build:
            context: .
            dockerfile: Dockerfile
        image: wordpress-production:local
        ports: 
            - "5110:2222"
        restart: unless-stopped
        depends_on: 
            - db
        volumes:
            - wp_data:/var/www/html
        environment: 
            SSH_PASSWORD: testing123
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            XDEBUG_CONFIG: remote_host=host.docker.internal
    nginx:
        image: nginx
        volumes:
            - wp_data:/usr/share/nginx/html:ro
            - ./conf.d:/etc/nginx/conf.d:consistent
            - ./log/nginx:/var/log/nginx
        depends_on: 
            - wordpress
        restart: unless-stopped
        ports: 
            - "5119:80"
volumes:
    db_data: {}
    wp_data: {}